# ~/.bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# BASH Setup
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize
shopt -s autocd

# Change Bash Prompt - https://bash-prompt-generator.org/
PROMPT_COMMAND='
  GIT_BRANCH=$(git branch --show-current 2>/dev/null)
  GIT_STATUS=$(git status --short 2>/dev/null)
  if [ -n "$GIT_BRANCH" ]; then
        if [ -n "$GIT_STATUS" ]; then
                PS1_GIT_INFO=$(printf "%b" "(\e[91m${GIT_BRANCH}\e[0m)\n\e[91m${GIT_STATUS}")
        else
                PS1_GIT_INFO=$(printf "%b" "(\e[91m${GIT_BRANCH}\e[0m)")
        fi
  else
    PS1_GIT_INFO=""
  fi'
PS1='\[\e[36m\]\u\[\e[94m\]@\h\[\e[93m\]:\w\[\e[0m\] ${PS1_GIT_INFO}\n  \[\e[31m\]\$\[\e[0m\] '

# Variables
export EDITOR='vim'

# Aliases
alias editBash="vim ~/.bashrc"
alias ls='ls --color=auto'
alias ll='ls -lA'
alias la='ls -A'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ip='ip -c'
alias cp='cp -r'
alias cu='cd ..'
alias cb='cd -'
alias mkdir='mkdir -p'
alias tree='tree -alC --dirsfirst'

# Functions
updateDebian(){
        echo ""
        echo "Updating Packages"
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt autoremove -y --purge

        # echo ""
        # echo "Updating Bashrc"
        # cd
        # rm -rf ~/.bashrc
        # curl --output ~/.bashrc https://raw.githubusercontent.com/masonperdue/linux-config/refs/heads/main/raspi/bashr

        # echo ""
        # echo "Sourcing ~/.bashrc"
        # source ~/.bashrc

        echo ""
}

myNmap(){
        # first argument should be target ip addr
        nmap -v -A -Pn -p 1-65535 "$1"
}

docScan(){
        # documents should be face down and upside down
        if [ -n "$1" ]; then
                cd ~/caddy/http/scan
                mkdir tmp
                cd tmp
                sudo scanimage --format=pnm --verbose --progress --resolution=300 --batch=out%03d.pnm --device='fujitsu:ScanSnap S1500:272145' --source 'ADF Duplex'
                # sudoedit /etc/ImageMagick*/policy.xml # change none to read|write for pdf and change memory to 4GiB
                convert out*.pnm -deskew 40% -density 150 -verbose $1.pdf
                mv $1.pdf ../
                sudo rm *.pnm
                cd ..
                sudo rmdir tmp
        else
                echo "Error: Input file name"
        fi
}

# Completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi