FROM debian:latest

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y unbound unbound-anchor unbound-host dns-root-data
RUN rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/lib/unbound && cp /usr/share/dns/root.key /var/lib/unbound/root.key

COPY custom.conf /etc/unbound/unbound.conf.d/custom.conf

RUN chown -R unbound:unbound /etc/unbound /var/lib/unbound

EXPOSE 53/udp 53/tcp

CMD ["unbound", "-d", "-p"]